version: '3.8'
services:
  feedback-service:
    image: melowetty/feedback-service
    depends_on:
      - postgresdb
    env_file: .env
    environment:
      - SPRING_PROFILES_ACTIVE=$ACTIVE_PROFILE
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:$POSTGRESDB_DOCKER_PORT/$DB_NAME
      - SPRING_DATASOURCE_USERNAME=$DB_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$DB_PASSWORD
      - KAFKA_BOOTSTRAP_SERVERS=$KAFKA_SERVERS
    restart: always
    networks:
      - internal
      - api-gateway_backend
      - message-broker_shared
    expose:
      - $SERVER_PORT
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - internal
volumes:
  db:
networks:
  internal:
  api-gateway_backend:
    external: true
  message-broker_shared:
    external: true