eureka:
  client:
    enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/feedback-service
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8082